//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var common_ttypes = require('./common_types');


var ttypes = module.exports = {};
ttypes.VERSION = '0.1.1';
ttypes.ERR_CODE = 39;
ttypes.SERVICE_NAME = 'dmp-service-encryptor';
ttypes.ENCRYPTION_PGP = 1;
