//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var common_ttypes = require('./common_types');


var BaseService = require('./BaseService');
var BaseServiceClient = BaseService.Client;
var BaseServiceProcessor = BaseService.Processor;
var ttypes = require('./encryptor_types');
//HELPER FUNCTIONS AND STRUCTURES

var PublicEncryptorService_encrypt_args = function(args) {
  this.ctx = null;
  this.ID = null;
  this.encryptionType = null;
  this.vfsID = null;
  if (args) {
    if (args.ctx !== undefined && args.ctx !== null) {
      this.ctx = new common_ttypes.Context(args.ctx);
    }
    if (args.ID !== undefined && args.ID !== null) {
      this.ID = args.ID;
    }
    if (args.encryptionType !== undefined && args.encryptionType !== null) {
      this.encryptionType = args.encryptionType;
    }
    if (args.vfsID !== undefined && args.vfsID !== null) {
      this.vfsID = args.vfsID;
    }
  }
};
PublicEncryptorService_encrypt_args.prototype = {};
PublicEncryptorService_encrypt_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ctx = new common_ttypes.Context();
        this.ctx.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.ID = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BYTE) {
        this.encryptionType = input.readByte();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.vfsID = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PublicEncryptorService_encrypt_args.prototype.write = function(output) {
  output.writeStructBegin('PublicEncryptorService_encrypt_args');
  if (this.ctx !== null && this.ctx !== undefined) {
    output.writeFieldBegin('ctx', Thrift.Type.STRUCT, 1);
    this.ctx.write(output);
    output.writeFieldEnd();
  }
  if (this.ID !== null && this.ID !== undefined) {
    output.writeFieldBegin('ID', Thrift.Type.STRING, 2);
    output.writeString(this.ID);
    output.writeFieldEnd();
  }
  if (this.encryptionType !== null && this.encryptionType !== undefined) {
    output.writeFieldBegin('encryptionType', Thrift.Type.BYTE, 3);
    output.writeByte(this.encryptionType);
    output.writeFieldEnd();
  }
  if (this.vfsID !== null && this.vfsID !== undefined) {
    output.writeFieldBegin('vfsID', Thrift.Type.STRING, 4);
    output.writeString(this.vfsID);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PublicEncryptorService_encrypt_result = function(args) {
  this.err = null;
  if (args instanceof common_ttypes.Error) {
    this.err = args;
    return;
  }
  if (args) {
    if (args.err !== undefined && args.err !== null) {
      this.err = args.err;
    }
  }
};
PublicEncryptorService_encrypt_result.prototype = {};
PublicEncryptorService_encrypt_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.err = new common_ttypes.Error();
        this.err.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PublicEncryptorService_encrypt_result.prototype.write = function(output) {
  output.writeStructBegin('PublicEncryptorService_encrypt_result');
  if (this.err !== null && this.err !== undefined) {
    output.writeFieldBegin('err', Thrift.Type.STRUCT, 1);
    this.err.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PublicEncryptorService_decrypt_args = function(args) {
  this.ctx = null;
  this.ID = null;
  this.encryptionType = null;
  this.vfsID = null;
  if (args) {
    if (args.ctx !== undefined && args.ctx !== null) {
      this.ctx = new common_ttypes.Context(args.ctx);
    }
    if (args.ID !== undefined && args.ID !== null) {
      this.ID = args.ID;
    }
    if (args.encryptionType !== undefined && args.encryptionType !== null) {
      this.encryptionType = args.encryptionType;
    }
    if (args.vfsID !== undefined && args.vfsID !== null) {
      this.vfsID = args.vfsID;
    }
  }
};
PublicEncryptorService_decrypt_args.prototype = {};
PublicEncryptorService_decrypt_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ctx = new common_ttypes.Context();
        this.ctx.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.ID = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.BYTE) {
        this.encryptionType = input.readByte();
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.vfsID = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PublicEncryptorService_decrypt_args.prototype.write = function(output) {
  output.writeStructBegin('PublicEncryptorService_decrypt_args');
  if (this.ctx !== null && this.ctx !== undefined) {
    output.writeFieldBegin('ctx', Thrift.Type.STRUCT, 1);
    this.ctx.write(output);
    output.writeFieldEnd();
  }
  if (this.ID !== null && this.ID !== undefined) {
    output.writeFieldBegin('ID', Thrift.Type.STRING, 2);
    output.writeString(this.ID);
    output.writeFieldEnd();
  }
  if (this.encryptionType !== null && this.encryptionType !== undefined) {
    output.writeFieldBegin('encryptionType', Thrift.Type.BYTE, 3);
    output.writeByte(this.encryptionType);
    output.writeFieldEnd();
  }
  if (this.vfsID !== null && this.vfsID !== undefined) {
    output.writeFieldBegin('vfsID', Thrift.Type.STRING, 4);
    output.writeString(this.vfsID);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PublicEncryptorService_decrypt_result = function(args) {
  this.err = null;
  if (args instanceof common_ttypes.Error) {
    this.err = args;
    return;
  }
  if (args) {
    if (args.err !== undefined && args.err !== null) {
      this.err = args.err;
    }
  }
};
PublicEncryptorService_decrypt_result.prototype = {};
PublicEncryptorService_decrypt_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.err = new common_ttypes.Error();
        this.err.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

PublicEncryptorService_decrypt_result.prototype.write = function(output) {
  output.writeStructBegin('PublicEncryptorService_decrypt_result');
  if (this.err !== null && this.err !== undefined) {
    output.writeFieldBegin('err', Thrift.Type.STRUCT, 1);
    this.err.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var PublicEncryptorServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Thrift.inherits(PublicEncryptorServiceClient, BaseServiceClient);
PublicEncryptorServiceClient.prototype.seqid = function() { return this._seqid; };
PublicEncryptorServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
PublicEncryptorServiceClient.prototype.encrypt = function(ctx, ID, encryptionType, vfsID, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_encrypt(ctx, ID, encryptionType, vfsID);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_encrypt(ctx, ID, encryptionType, vfsID);
  }
};

PublicEncryptorServiceClient.prototype.send_encrypt = function(ctx, ID, encryptionType, vfsID) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('encrypt', Thrift.MessageType.CALL, this.seqid());
  var args = new PublicEncryptorService_encrypt_args();
  args.ctx = ctx;
  args.ID = ID;
  args.encryptionType = encryptionType;
  args.vfsID = vfsID;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

PublicEncryptorServiceClient.prototype.recv_encrypt = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new PublicEncryptorService_encrypt_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.err) {
    return callback(result.err);
  }
  callback(null);
};
PublicEncryptorServiceClient.prototype.decrypt = function(ctx, ID, encryptionType, vfsID, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_decrypt(ctx, ID, encryptionType, vfsID);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_decrypt(ctx, ID, encryptionType, vfsID);
  }
};

PublicEncryptorServiceClient.prototype.send_decrypt = function(ctx, ID, encryptionType, vfsID) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('decrypt', Thrift.MessageType.CALL, this.seqid());
  var args = new PublicEncryptorService_decrypt_args();
  args.ctx = ctx;
  args.ID = ID;
  args.encryptionType = encryptionType;
  args.vfsID = vfsID;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

PublicEncryptorServiceClient.prototype.recv_decrypt = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new PublicEncryptorService_decrypt_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.err) {
    return callback(result.err);
  }
  callback(null);
};
var PublicEncryptorServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
Thrift.inherits(PublicEncryptorServiceProcessor, BaseServiceProcessor);
PublicEncryptorServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
PublicEncryptorServiceProcessor.prototype.process_encrypt = function(seqid, input, output) {
  var args = new PublicEncryptorService_encrypt_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.encrypt.length === 4) {
    Q.fcall(this._handler.encrypt, args.ctx, args.ID, args.encryptionType, args.vfsID)
      .then(function(result) {
        var result_obj = new PublicEncryptorService_encrypt_result({success: result});
        output.writeMessageBegin("encrypt", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof common_ttypes.Error) {
          result = new PublicEncryptorService_encrypt_result(err);
          output.writeMessageBegin("encrypt", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("encrypt", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.encrypt(args.ctx, args.ID, args.encryptionType, args.vfsID, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof common_ttypes.Error) {
        result_obj = new PublicEncryptorService_encrypt_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("encrypt", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("encrypt", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
PublicEncryptorServiceProcessor.prototype.process_decrypt = function(seqid, input, output) {
  var args = new PublicEncryptorService_decrypt_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.decrypt.length === 4) {
    Q.fcall(this._handler.decrypt, args.ctx, args.ID, args.encryptionType, args.vfsID)
      .then(function(result) {
        var result_obj = new PublicEncryptorService_decrypt_result({success: result});
        output.writeMessageBegin("decrypt", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof common_ttypes.Error) {
          result = new PublicEncryptorService_decrypt_result(err);
          output.writeMessageBegin("decrypt", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("decrypt", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.decrypt(args.ctx, args.ID, args.encryptionType, args.vfsID, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof common_ttypes.Error) {
        result_obj = new PublicEncryptorService_decrypt_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("decrypt", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("decrypt", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
