//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var common_ttypes = require('./common_types');


var PublicResourceManager = require('./PublicResourceManager');
var PublicResourceManagerClient = PublicResourceManager.Client;
var PublicResourceManagerProcessor = PublicResourceManager.Processor;
var ttypes = require('./resource_manager_types');
//HELPER FUNCTIONS AND STRUCTURES

var ResourceManager_changeStatus_args = function(args) {
  this.ctx = null;
  this.toolID = null;
  this.newStatus = null;
  if (args) {
    if (args.ctx !== undefined && args.ctx !== null) {
      this.ctx = new common_ttypes.Context(args.ctx);
    }
    if (args.toolID !== undefined && args.toolID !== null) {
      this.toolID = args.toolID;
    }
    if (args.newStatus !== undefined && args.newStatus !== null) {
      this.newStatus = args.newStatus;
    }
  }
};
ResourceManager_changeStatus_args.prototype = {};
ResourceManager_changeStatus_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ctx = new common_ttypes.Context();
        this.ctx.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.toolID = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.newStatus = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResourceManager_changeStatus_args.prototype.write = function(output) {
  output.writeStructBegin('ResourceManager_changeStatus_args');
  if (this.ctx !== null && this.ctx !== undefined) {
    output.writeFieldBegin('ctx', Thrift.Type.STRUCT, 1);
    this.ctx.write(output);
    output.writeFieldEnd();
  }
  if (this.toolID !== null && this.toolID !== undefined) {
    output.writeFieldBegin('toolID', Thrift.Type.STRING, 2);
    output.writeString(this.toolID);
    output.writeFieldEnd();
  }
  if (this.newStatus !== null && this.newStatus !== undefined) {
    output.writeFieldBegin('newStatus', Thrift.Type.STRING, 3);
    output.writeString(this.newStatus);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResourceManager_changeStatus_result = function(args) {
  this.err = null;
  if (args instanceof common_ttypes.Error) {
    this.err = args;
    return;
  }
  if (args) {
    if (args.err !== undefined && args.err !== null) {
      this.err = args.err;
    }
  }
};
ResourceManager_changeStatus_result.prototype = {};
ResourceManager_changeStatus_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.err = new common_ttypes.Error();
        this.err.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ResourceManager_changeStatus_result.prototype.write = function(output) {
  output.writeStructBegin('ResourceManager_changeStatus_result');
  if (this.err !== null && this.err !== undefined) {
    output.writeFieldBegin('err', Thrift.Type.STRUCT, 1);
    this.err.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ResourceManagerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Thrift.inherits(ResourceManagerClient, PublicResourceManagerClient);
ResourceManagerClient.prototype.seqid = function() { return this._seqid; };
ResourceManagerClient.prototype.new_seqid = function() { return this._seqid += 1; };
ResourceManagerClient.prototype.changeStatus = function(ctx, toolID, newStatus, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_changeStatus(ctx, toolID, newStatus);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_changeStatus(ctx, toolID, newStatus);
  }
};

ResourceManagerClient.prototype.send_changeStatus = function(ctx, toolID, newStatus) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('changeStatus', Thrift.MessageType.CALL, this.seqid());
  var args = new ResourceManager_changeStatus_args();
  args.ctx = ctx;
  args.toolID = toolID;
  args.newStatus = newStatus;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ResourceManagerClient.prototype.recv_changeStatus = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ResourceManager_changeStatus_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.err) {
    return callback(result.err);
  }
  callback(null);
};
var ResourceManagerProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
Thrift.inherits(ResourceManagerProcessor, PublicResourceManagerProcessor);
ResourceManagerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
ResourceManagerProcessor.prototype.process_changeStatus = function(seqid, input, output) {
  var args = new ResourceManager_changeStatus_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.changeStatus.length === 3) {
    Q.fcall(this._handler.changeStatus, args.ctx, args.toolID, args.newStatus)
      .then(function(result) {
        var result_obj = new ResourceManager_changeStatus_result({success: result});
        output.writeMessageBegin("changeStatus", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof common_ttypes.Error) {
          result = new ResourceManager_changeStatus_result(err);
          output.writeMessageBegin("changeStatus", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("changeStatus", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.changeStatus(args.ctx, args.toolID, args.newStatus, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof common_ttypes.Error) {
        result_obj = new ResourceManager_changeStatus_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("changeStatus", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("changeStatus", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
