//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var common_ttypes = require('./common_types');


var ttypes = module.exports = {};
ttypes.VERSION = '0.1.0';
ttypes.ERR_CODE = 161;
ttypes.SERVICE_NAME = '4cas-session';
ttypes.ATTR_KEY_GROUPS = 'groups';
ttypes.ATTR_KEY_PCAS = 'pcas';
ttypes.ATTR_PW_CHANGE = 'pw_change_supported';
