//
// Autogenerated by Thrift Compiler (0.10.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var common_ttypes = require('./common_types');
var vfs_ttypes = require('./vfs_types');


var ttypes = module.exports = {};
ttypes.SERVICE_NAME = 'dmp-service-workspace';
ttypes.VFS_FOLDER_NAME = 'Workspace';
ttypes.VERSION = '0.2.1';
ttypes.AMQP_ROUTING_KEY = 'dmp.events.workspace';
ttypes.ERR_CODE = 35;
